djangoblog/djangonautic/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

djangoblog/djangonautic/articles/urls.py
from django.urls import path, re_path
from . import views

# Has the app_name before every URL in urlpatterns
app_name = 'articles'
urlpatterns = [
    path('', views.article_list, name='article-list'),
    path('create/', views.article_create, name='article-create'),
    path('search/', views.SearchView.as_view(), name='search-results'),
    path('<slug:slug>/', views.article_detail, name='article-detail'),
    path('update/<int:userid>/', views.article_list_of_author, name='article-list-of-author'),
    path('delete/<int:articleid>', views.article_delete, name='article-delete'),
    path('update/<int:userid>/<int:articleid>/', views.article_update, name='article-update'),
]

djangoblog/djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', article_list, name='home'),

    # REST FRAMEWORK URLs
    path('api/articles/', include('articles.api.urls', 'articles_api')),
    path('api/accounts/', include('accounts.api.urls', 'account_signup_api')),
]

# Add this after adding STATIC_URL and STAIC_DIRS in settings.py
urlpatterns += staticfiles_urlpatterns()

# Add this after adding MEDIA URL and MEDIA_ROOT in settings.py
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoblog/djangonautic/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Djangonautic!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a>
        </div>
        <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
            <li><a href="{% url 'articles:article-create' %}" class="highlight">New Post</a></li>
            <li><a href="{% url 'articles:article-list-of-author' userid=user.id %}" class="highlight">Update Posts</a></li>
            <li>
                <form class="logout-link" method="POST" action="{% url 'accounts:logout' %}"> {% csrf_token %}
                    <button type="submit" class="errorlist-delete logout">Logout</button>
                </form>
            </li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}" class="highlight">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}" class="highlight">Signup</a></li>
            {% endif %}

            <form class="form-inline my-2 my-lg-0 search-form" action="{% url 'articles:search-results' %}" method="GET">
            <div class="active-cyan-3 active-cyan-4 mb-4">
                <input class="form-control" type="text" placeholder="Search..." name="q" onfocus="this.placeholder=''" onblur="this.placeholder='Search...'">
            </div>
            </form>
        </ul>
    </div>
    </nav>
    <div class="wrapper">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="page-footer pt-4">
        <div class="container-fluid text-center text-md-left upper-footer">
            <div class="row">
                <div class="col-md-3 mt-md-0 mt-3 img-div">
                    <img class="footer-img" src="{% static 'logo.png' %}"></a>
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-6 mb-md-0 mb-3">
                    <h5 class="footer-headings">Motivation For Djangonautic</h5>
                    <p> Initially, this blog was developed as a practice for understanding Python's Django Web Framework.
                        The blog was built and designed via The Net Ninja's Django Blog tutorial. After completion,
                        I added more functionality to it, improved the design as well as the blog's overall
                        User Experience.
                    </p>
                    <h5 class="footer-headings">Added Django REST Support</h5>
                    <p> The blog also has API support implemented through the Django REST framework. The API support
                        was added by taking inspiration from Coding With Mitch and Parwiz Forough's Django REST tutorials.
                    </p>
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-2 mb-md-0 mb-3">
                    <h5 class="footer-headings">Link To Tutorials</h5>
                    <p><a href="https://www.youtube.com/watch?v=n-FTlQ7Djqc&list=PL4cUxeGkcC9ib4HsrXEYpQnTOTZE1x0uc">The Net Ninja</a></p>
                    <p><a href="https://www.youtube.com/playlist?list=PLgCYzUzKIBE9Pi8wtx8g55fExDAPXBsbV">Coding With Mitch</a></p>
                    <p><a href="https://www.youtube.com/watch?v=B38aDwUpcFc&t=4496s">Parwiz Forogh Django REST</a></p>
                    <br>
                    <p>Python 3.6.9 - Django 3.0.5</p>
                    <p>Django REST 3.11.0</p>
                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">© Copyright 2020 -
            <script>
                var today = new Date();
                document.write(today.getFullYear());
            </script>
        </div>
    </footer>
</body>
</html>