djangoblog/djangonautic/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

djangoblog/djangonautic/articles/api/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.ArticleAPIView.as_view(), name='articles-list-and-post-apiurl'),
    path('<int:id>/', views.ArticleAPIView.as_view(), name='get-apiurl'),
    path('<int:id>/update/', views.ArticleAPIView.as_view(), name='update-apiurl'),
    path('<int:id>/delete/', views.ArticleAPIView.as_view(), name='delete-apiurl'),
    path('list/', views.ArticlesPaginationView.as_view(), name='pagination-url'),
]

djangoblog/djangonautic/articles/urls.py
from django.urls import path, re_path
from . import views

# Has the app_name before every URL in urlpatterns
app_name = 'articles'
urlpatterns = [
    path('', views.article_list, name='article-list'),
    path('create/', views.article_create, name='article-create'),
    path('search/', views.SearchView.as_view(), name='search-results'),
    path('<slug:slug>/', views.article_detail, name='article-detail'),
    path('update/<int:userid>/', views.article_list_of_author, name='article-list-of-author'),
    path('delete/<int:articleid>', views.article_delete, name='article-delete'),
    path('update/<int:userid>/<int:articleid>/', views.article_update, name='article-update'),
]

djangoblog/djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', article_list, name='home'),

    # REST FRAMEWORK URLs
    path('api/articles/', include('articles.api.urls', 'articles_api')),
    path('api/accounts/', include('accounts.api.urls', 'account_signup_api')),
]

# Add this after adding STATIC_URL and STAIC_DIRS in settings.py
urlpatterns += staticfiles_urlpatterns()

# Add this after adding MEDIA URL and MEDIA_ROOT in settings.py
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoblog/djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
class Article(models.Model):
    slug   = models.SlugField(unique=True)
    body   = models.TextField()
    date   = models.DateTimeField(auto_now_add=True)
    title  = models.CharField(max_length=100)
    thumb  = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:150] + '...'

djangoblog/djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model  = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

djangoblog/djangonautic/articles/api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework import mixins
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination
from rest_framework.filters import SearchFilter, OrderingFilter
from django.contrib.auth.models import User

from ..models import Article
from .serializers import ArticleSerializer


@permission_classes((IsAuthenticated,))
class ArticleAPIView(APIView):

    def get(self, request, id=None):
        if id is not None:
            article    = Article.objects.get(id=id)
            serializer = ArticleSerializer(article)
            return Response(serializer.data)
        articles   = Article.objects.all()
        serializer = ArticleSerializer(articles, many=True)
        return Response(serializer.data)

    def post(self, request):
        author     = User.objects.get(id=request.user.id)
        article    = Article(author=author)
        serializer = ArticleSerializer(article, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, id):
        try:
            article = Article.objects.get(id=id)
        except Article.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        if article.author != request.user:
            return Response({'Permission Denied': 'You cannot update this article!'}, status=status.HTTP_400_BAD_REQUEST)

        serializer = ArticleSerializer(article, request.data)
        if serializer.is_valid():
            serializer.save()

            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, id):
        try:
            article = Article.objects.get(id=id)
        except Article.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        if article.author != request.user:
            return Response({'Permission Denied': 'You cannot delete this article!'}, status=status.HTTP_400_BAD_REQUEST)

        article.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ArticlesPaginationView(generics.ListAPIView):
    queryset               = Article.objects.all()
    serializer_class       = ArticleSerializer
    pagination_class       = PageNumberPagination
    permission_classes     = (IsAuthenticated,)
    authentication_classes = (TokenAuthentication,)
    filter_backends        = (SearchFilter, OrderingFilter)
    search_fields          = ('title', 'body', 'thumb', 'author__username')

djangoblog/djangonautic/articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.db.models import Q
from django.http import HttpResponse

from .models import Article
from . import forms


def article_list(request):
    articles = Article.objects.all().order_by('-date')
    context  = {
        'articles':articles
    }
    return render(request, 'articles/article_list.html', context)


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    context = {
        'article':article
    }
    return render(request, 'articles/article_detail.html', context)


@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # Commit = False means to wait for a moment but give us the save instance
            instance        = form.save(commit=False)
            instance.author = request.user
            # Appending author to slug so that different users can post articles with the same names
            instance.slug = instance.author.username + '-' + form.cleaned_data['slug']
            instance.save()

            return redirect('articles:article-list')
    else:
        form = forms.CreateArticle()
    context = {
        'form':form
    }
    return render(request, 'articles/article_create.html', context)


def article_list_of_author(request, userid):
    articles = Article.objects.filter(author=userid).order_by('-date')
    context  = {
        'articles':articles
    }
    return render(request, 'articles/user_articles.html', context)


def article_update(request, userid, articleid):
    if request.method == 'POST':
        article = get_object_or_404(Article, id=articleid)
        form    = forms.CreateArticle(request.POST or None, request.FILES, instance=article)
        if form.is_valid():
            instance      = form.save(commit=False)
            instance.slug = instance.author.username + '-' + form.cleaned_data['slug']
            instance.save()
            return redirect('articles:article-list')
    else:
        article = get_object_or_404(Article, id=articleid)
        form    = forms.CreateArticle(request.GET or None, instance=article)
    context = {
        'form':form,
    }

    return render(request, 'articles/article_update.html', context)


def article_delete(request, articleid):
    article = get_object_or_404(Article, id=articleid)
    context = {}
    if request.method == 'POST':
        if 'confirm delete' in request.POST:
            # if condition checks if POST request is coming from article_delete.html
            # by clicking the Confirm Delete button
            article.delete()
            return redirect('articles:article-list')
        else:
            context = {
                'article': article
            }

    return render(request, 'articles/article_delete.html', context)


class SearchView(ListView):
    model         = Article
    template_name = 'articles/search_results.html'

    def get_queryset(self):
        articles = []
        query    = self.request.GET['q']
        query    = query.split(' ')
        for word in query:
            filtered_articles = Article.objects.filter(
                Q(title__icontains=word) | Q(body__icontains=word) |
                Q(author__username__icontains=word) | Q(thumb__icontains=word)
            ).order_by('-date')

            # For removing duplicate articles fetched by the above filters
            for article in filtered_articles:
                if article not in articles:
                    articles.append(article)

        return articles

djangoblog/djangonautic/articles/templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
<div class="article-create">
    <h2>Post New Article</h2>
    <form class="site-form" method="POST" enctype="multipart/form-data"> {% csrf_token %}
<!-- enctype always required for upload fields.
action="{% url 'articles:article-create' %}"-->
        {{ form.as_p }}
        <input type="submit" value="Post">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/article_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="article-create">
    <h2>Delete Article</h2>
    <form method="POST" class="site-form delete-form"> {% csrf_token %}
        <p>Are you sure you want to delete this article?</p>
        <p>Title: {{ article.title }}</p>
        <p>Author: {{ article.author }}</p>
        <input type="submit" value="Confirm Delete" name="confirm delete"><br>
        <button class="back-button" onclick="goBack()">Back</button>
    </form>
    <script>
    function goBack() {
        window.history.back();
    }
    </script>
</div>
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <img src="{{ article.thumb.url }}">
        <p>{{ article.body }}</p>
        <p>Published On: {{ article.date }}</p>
    </div>
    {% ifequal user article.author  %}
    <form class="site-form delete-form" method="POST" action="{% url 'articles:article-delete' article.id %}">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
    {% endifequal %}
</div>
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome To Djangonautic!</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <a href="{% url 'articles:article-detail' slug=article.slug %}">
            <img src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
        </a>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">Added By: {{ article.author }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/article_update.html
{% extends 'base.html' %}

{% block content %}
<div class="article-create">
    <h2>Update Your Article</h2>
    <form class="site-form" method="POST" enctype="multipart/form-data"> {% csrf_token %}
<!-- enctype always required for upload fields.
action="{% url 'articles:article-create' %}"-->
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/search_results.html
{% extends 'base.html' %}

{% block content %}
{% if object_list %}
<h1>Search Results</h1>
<div class="articles">
    {% for article in object_list %}
    <div class="article">
        <a href="{% url 'articles:article-detail' slug=article.slug %}">
            <img src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
        </a>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">Added By: {{ article.author }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<h1 class="not-found">Whoops! Your Search Returned Nothing.</h1>
{% endif %}
{% endblock %}

djangoblog/djangonautic/articles/templates/articles/user_articles.html
{% extends 'base.html' %}

{% block content %}
{% if articles %}
<h1>Your Articles</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <a href="{% url 'articles:article-update' user.id article.id %}">
            <img src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
        </a>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">Added By: {{ article.author }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<h1 class="not-found">You Currently Don't Have Any Posts.</h1>
{% endif %}
{% endblock %}